services:
    ollama_server:
        build: ./ollama_server
        network_mode: host
        ports:
            - 11434:11434
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
    telebot_service:
        build: ./telebot
        network_mode: host
